HADOOP_HOME=$HOME/Applications/hadoop
if [ -d "$HADOOP_HOME" ]; then
    HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
    LD_LIBRARY_PATH=$HADOOP_HOME/lib/native:$LD_LIBRARY_PATH
    PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bin
    export HADOOP_HOME HADOOP_CONF_DIR LD_LIBRARY_PATH PATH
fi
